name: PR Checks

on:
  push:
    branches:
      - 'prerelease/**'

jobs:
  code-format:
    name: Code Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Setup Node.js
        with:
          node-version: "18.x"
      - name: Setup yarn
        run: npm install -g yarn
      - run: yarn
      - run: yarn ci:code-formatting
  code-style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Setup Node.js
        with:
          node-version: "18.x"
      - name: Setup yarn
        run: npm install -g yarn
      - run: yarn
      - run: yarn ci:code-style
  build:
    name: build check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: "18.x"
      - name: Setup yarn
        run: npm install -g yarn
      - run: yarn install --immutable
      - run: npm version prepatch --preid=alpha
      - run: yarn build
      - run: npm publish
